/**
 * Canonical Pakistan location data for Mint Rewards.
 *
 * SINGLE SOURCE OF TRUTH. Every province, city, town and sub-area option shown
 * anywhere in the app must come from this data via the helpers in
 * `pakistan_areas.ts`. Do not hardcode, infer or duplicate any of these names.
 *
 * Hierarchy: province -> city -> town -> subArea.
 *
 * `subAreas` is keyed by a composite "City::Town" string rather than by town
 * name alone: town names such as "Cantt", "Satellite Town" and "Model Town"
 * repeat across cities, so a town-only key would collide. Always go through
 * `getSubAreasForTown(city, town)`.
 *
 * THIS FILE HOLDS RAW DATA ONLY. No logic, no metadata, no imports.
 *
 * It was split out of `pakistan_areas.ts` after a metadata edit anchored on the
 * string "Cantonment" landed in QUETTA's town array instead of the coarse-unit
 * set it was aimed at — Quetta has a town by that name. The declared-count
 * assertion caught it, but the two structures had no business being adjacent
 * and greppable as one file. Now a mis-anchored metadata edit cannot physically
 * reach the data.
 *
 * NEVER edit or delete a string here. `isLegacyTownValue` treats any stored
 * town outside this list as stale, so a rename force-marches every profile
 * holding it through LocationUpdateModal. Additions are safe; retirements go
 * through DEPRECATED_TOWNS / DEPRECATED_SUB_AREAS in `pakistan_areas.ts`.
 *
 * Originally generated 2026-08-05 from the since-removed pakistan_areas.json
 * (City -> Area -> Sub-areas, version 1.0, 2026-07-24), whose area names the
 * town lists were aligned to. That JSON is gone; this file is now hand-owned
 * and is the only copy.
 */
export interface LocationData {
  provinces: string[];
  cities: Record<string, string[]>;
  towns: Record<string, string[]>;
  /** Keyed by `${city}::${town}` — see note above. */
  subAreas: Record<string, string[]>;
}

export const PAKISTAN_LOCATIONS: LocationData = {
  provinces: [
    "Punjab",
    "Sindh",
    "Khyber Pakhtunkhwa",
    "Balochistan",
    "Islamabad Capital Territory",
    "Azad Jammu & Kashmir",
    "Gilgit-Baltistan",
  ],

  cities: {
    Punjab: [
      "Lahore",
      "Faisalabad",
      "Rawalpindi",
      "Gujranwala",
      "Multan",
      "Sialkot",
      "Bahawalpur",
      "Sargodha",
      "Sheikhupura",
      "Jhang",
      "Gujrat",
      "Rahim Yar Khan",
      "Kasur",
      "Dera Ghazi Khan",
      "Sahiwal",
    ],
    Sindh: [
      "Karachi",
      "Hyderabad",
      "Sukkur",
      "Larkana",
      "Nawabshah",
      "Mirpur Khas",
      "Jacobabad",
      "Shikarpur",
      "Khairpur",
      "Thatta",
    ],
    "Khyber Pakhtunkhwa": [
      "Peshawar",
      "Mardan",
      "Mingora",
      "Kohat",
      "Abbottabad",
      "Mansehra",
      "Dera Ismail Khan",
      "Swabi",
      "Nowshera",
      "Charsadda",
    ],
    Balochistan: [
      "Quetta",
      "Turbat",
      "Khuzdar",
      "Hub",
      "Chaman",
      "Gwadar",
      "Dera Murad Jamali",
      "Sibi",
      "Zhob",
      "Loralai",
    ],
    "Islamabad Capital Territory": [
      "Islamabad",
    ],
    "Azad Jammu & Kashmir": [
      "Muzaffarabad",
      "Mirpur",
      "Rawalakot",
      "Kotli",
      "Bhimber",
      "Bagh",
    ],
    "Gilgit-Baltistan": [
      "Gilgit",
      "Skardu",
      "Chilas",
      "Hunza",
      "Ghanche",
      "Ghizer",
    ],
  },

  towns: {
    Lahore: [
      "DHA Lahore",
      "Bahria Town Lahore",
      "Gulberg",
      "Model Town",
      "Johar Town",
      "Wapda Town",
      "Garden Town",
      "Township",
      "Cantt",
      "Iqbal Town",
      "Faisal Town",
      "EME Society",
      "Valencia Town",
      "PCSIR Housing Scheme",
      "Punjab Cooperative Housing Society (PCHS)",
      "Cavalry Ground",
      "Sui Gas Society",
      "Lake City",
      "State Life Housing Society",
      "PGEHS (Punjab Govt Employees Housing Scheme)",
      "LDA Avenue",
      "Jubilee Town",
      "Sabzazar",
      "Shahdara",
      "Shadman",
      "Samanabad",
      "Raiwind",
    ],
    Karachi: [
      "DHA",
      "Clifton",
      "PECHS",
      "Gulshan-e-Iqbal",
      "Gulistan-e-Jauhar",
      "North Karachi",
      "North Nazimabad",
      "Nazimabad",
      "Federal B. Area",
      "Liaquatabad",
      "Korangi",
      "Landhi",
      "Malir",
      "Shah Faisal Colony",
      "Bahria Town Karachi",
      "Askari",
      "Buffer Zone",
      "Gulshan-e-Hadeed",
      "Garden",
      "Orangi Town",
      "Saddar",
      "KAECHS",
      "Gulshan-e-Maymar",
      "Scheme 33",
      "New Karachi",
      "Defence View",
      "Gulzar-e-Hijri",
      "Surjani Town",
      "Naya Nazimabad",
      // --- P0.6 registry expansion (2026-08-25) ---------------------------
      // 53% of 1,000 uniformly sampled Karachi points named a real place with
      // no registry entry. Everything below is ADDITIVE: not one existing
      // string is touched, because `isLegacyTownValue` treats any stored town
      // outside this list as stale and would force those users to re-pick.
      // Each entry carries the evidence that admitted it.
      // Industrial and port estates. Not homes, but addresses: B2B waste clients
      // and MintTrace's industrial operators sit here, and without these the
      // registry cannot express a client site at all. Flagged non-residential,
      // which swaps the house-number field to "Unit / building name".
      "Korangi Industrial Area",   // OSM 25 / Google 25
      "Sindh Industrial Trading Estate",   // OSM 8 / Google 33
      "West Wharf",   // OSM 7 / Google 7
      // Named independently by BOTH Google and OSM at the same coordinate. The
      // strongest provenance available here.
      "Manora",   // OSM 7 / Google 5
      "Lalazar",   // OSM 6 / Google 3
      "Shanti Nagar",   // OSM 5 / Google 3
      "Agra Taj Colony",   // OSM 5 / Google 1
      "Daryabad",   // OSM 4 / Google 2
      "Ramswami",   // OSM 4 / Google 1
      "Sultanabad",   // OSM 3 / Google 2
      "FC Area",   // OSM 2 / Google 3
      "Baloch Colony",   // OSM 2 / Google 2
      "Jamshed Quarters",   // OSM 2 / Google 2
      "Pathan Colony",   // OSM 2 / Google 5
      "Bath Island",   // OSM 1 / Google 2
      "Machar Colony",   // OSM 1 / Google 4
      // OSM-sourced (ODbL, no restriction on reuse), >=2 sampled points each.
      // These never appeared in Google's list at all -- they are additional
      // coverage the Google-only triage would have missed entirely.
      "Drigh Colony",   // OSM 18
      "Metroville",   // OSM 17
      "Karsaz",   // OSM 16
      "Gulshan-e-Shamim",   // OSM 16
      "Muslimabad",   // OSM 13
      "Sikandarabad",   // OSM 8
      "Sachal Goth",   // OSM 7
      "Essa Nagri",   // OSM 7
      "Golimar",   // OSM 6
      "Old Golimar",   // OSM 1, at coordinates distinct from Golimar
      // Askari 1-5 are five separate towns in different parts of Karachi, not
      // one town with five sub-areas. The sweep put Askari 4 at 24.899,67.117
      // and Askari 5 at 24.940,67.179 — about 8 km apart. The bare "Askari"
      // entry above cannot be removed (frozen), so it is deprecated instead:
      // see DEPRECATED_TOWNS.
      "Askari 1",
      "Askari 2",
      "Askari 3",
      "Askari 4",
      "Askari 5",
      // "Garden" is not a place. Garden East and Garden West are separate
      // localities, and Soldier Bazaar — the third entry in the old Garden
      // sub-area list — is one too. Retiring the container without promoting
      // all three would strand Soldier Bazaar with no way to select it.
      "Garden East",
      "Garden West",
      "Soldier Bazaar",
      "Steel Town",   // owner-confirmed: a separate residential area
      "Shah Latif Town",   // owner-confirmed: its own town, NOT a sub-area
      "Bin Qasim Town",    // owner-confirmed: selectable in its own right
      "Gulshan-e-Ghazi",   // OSM 5
      "Mahmudabad",   // OSM 5
      "Darussalam Society",   // OSM 5
      "Jacob Lines",   // OSM 4
      "Jutland Lines",   // OSM 4
      "Pioneer Park City",   // OSM 4
      "Altaf Town",   // OSM 4
      "Tariq Bin Ziyad Colony",   // OSM 3
      "New Rizvia Society",   // OSM 3
      "Alamgir Society",   // OSM 3
      "Azam Basti",   // OSM 3
      "Gulshan-e-Umer",   // OSM 3
      "Dawood Cooperative Housing Society",   // OSM 3
      "P&T Society",   // OSM 2
      "Karli",   // OSM 2
      "Bahadurabad",   // OSM 2
      "Saeedabad",   // OSM 2
      "Goth Dad Muhammad",   // OSM 2
      "Miran Naka",   // OSM 2
      "Memon Nagar",   // OSM 2
      "Rexber Colony",   // OSM 2
      "Khadda Memon",   // OSM 2
      "Kalakot",   // OSM 2
      "Patel Para",   // OSM 2
      // Google-named, OSM silent at those coordinates, confirmed by general
      // knowledge as the plan allows. Ibrahim Hyderi is the single largest
      // residential gap in the sweep at 35 points.
      "Ibrahim Hyderi",   // Google 35; OSM silent at those points
      "Qayyumabad",   // Google 6; OSM silent at those points
      "Sher Shah Colony",   // Google 6 / OSM 1
    ],
    Islamabad: [
      "Sector E-7",
      "Sector E-8",
      "Sector E-9",
      "Sector E-10",
      "Sector E-11",
      "Sector E-12",
      "Sector E-16",
      "Sector E-17",
      "Sector F-5",
      "Sector F-6",
      "Sector F-7",
      "Sector F-8",
      "Sector F-9 (Fatima Jinnah Park)",
      "Sector F-10",
      "Sector F-11",
      "Sector F-17",
      "Sector G-5",
      "Sector G-6",
      "Sector G-7",
      "Sector G-8",
      "Sector G-9",
      "Sector G-10",
      "Sector G-11",
      "Sector G-12",
      "Sector G-13",
      "Sector G-14",
      "Sector G-15",
      "Sector G-16",
      "Sector H-8",
      "Sector H-9",
      "Sector H-10",
      "Sector H-11",
      "Sector H-12",
      "Sector H-13",
      "Sector I-8",
      "Sector I-9",
      "Sector I-10",
      "Sector I-11",
      "Sector I-12",
      "Sector I-14",
      "Sector I-15",
      "Sector I-16",
      "Blue Area",
      "Sector D-12",
      "Sector D-17",
      "Sector C-14",
      "Sector C-15",
      "Sector B-17",
      "DHA Islamabad",
      "Bahria Town Islamabad",
      "PWD Housing Scheme",
      "Pakistan Town",
      "CBR Town",
      "Gulberg Greens",
      "Gulberg Residencia",
      "Top City",
      "Capital Smart City",
      "Bani Gala",
      "Margalla Town",
    ],
    Rawalpindi: [
      "Satellite Town",
      "Bahria Town Phase 8",
      "Chaklala Scheme 3",
      "Askari",
      "Westridge",
      "Adiala Road",
      "Saddar",
      "Rawalpindi Cantt",
      "Bahria Town",
      "DHA",
      "Chaklala",
      "Gulzar-e-Quaid",
      "Gulshan Abad",
      "Raja Bazaar",
      "Pirwadhai",
    ],
    Faisalabad: [
      "Peoples Colony",
      "Madina Town",
      "Gulberg",
      "Samanabad",
      "Ghulam Muhammad Abad",
      "Batala Colony",
      "Jinnah Colony",
      "Eden Valley",
      "Citi Housing",
      "Wapda City",
      "Susan Road",
      "Millat Town",
      "Canal Road",
      "Tariq Abad",
      "Civil Lines",
    ],
    Peshawar: [
      "Hayatabad",
      "University Town",
      "Peshawar Cantt",
      "DHA Peshawar",
      "Regi Model Town",
      "Warsak Road",
      "Saddar",
      "Gulbahar",
      "Khyber Bazaar",
      "Chamkani",
      "Pabbi",
      "Ring Road",
    ],
    Quetta: [
      "Satellite Town",
      "Cantonment",
      "Samungli",
      "Jinnah Town",
      "Zarghoon Road",
      "Sariab Road",
      "Brewery Road",
      "Airport Road",
      "Spinny Road",
      "Adalat Road",
    ],
    Multan: [
      "DHA Multan",
      "Bosan Road",
      "Shah Rukn-e-Alam Colony",
      "Gulgasht Colony",
      "Wapda Town",
      "Officers Colony",
      "Model Town",
      "Citi Housing Multan",
      "Cantt",
      "Nawan Shehr",
      "Qasim Bela",
      "Old Multan",
      "Shujabad Road",
    ],
    Hyderabad: [
      "Latifabad",
      "Qasimabad",
      "Cantonment",
      "Gulshan-e-Shahbaz",
      "Saddar",
      "Hirabad",
      "Kotri",
      "Hussainabad",
      "New Hyderabad",
    ],
    Gujranwala: [
      "Cantt",
      "Satellite Town",
      "Model Town",
      "Peoples Colony",
      "Trust Colony",
      "Shabbir Colony",
      "Civil Lines",
    ],
  },

  subAreas: {
    "Lahore::DHA Lahore": [
      "Phase 1",
      "Phase 2",
      "Phase 3",
      "Phase 4",
      "Phase 5",
      "Phase 5 - Block A",
      "Phase 5 - Block B",
      "Phase 5 - Block C",
      "Phase 5 - Block D",
      "Phase 5 - Block E",
      "Phase 5 - Block F",
      "Phase 5 - Block G",
      "Phase 5 - Block H",
      "Phase 5 - Block J",
      "Phase 5 - Block K",
      "Phase 5 - Block L",
      "Phase 6",
      "Phase 6 - Block A",
      "Phase 6 - Block B",
      "Phase 6 - Block C",
      "Phase 6 - Block D",
      "Phase 6 - Block E",
      "Phase 6 - Block F",
      "Phase 6 - Block G",
      "Phase 6 - Block H",
      "Phase 6 - Block J",
      "Phase 6 - Block K",
      "Phase 7",
      "Phase 8",
      "Phase 8 - Block A",
      "Phase 8 - Block B",
      "Phase 8 - Block C",
      "Phase 8 - Block D",
      "Phase 8 - Block S",
      "Phase 8 - Block T",
      "Phase 8 - Block U",
      "Phase 8 - Block V",
      "Phase 8 - Block W",
      "Phase 9 Town",
      "Phase 9 Prism",
      "Phase 10",
      "Phase 11 (Rahbar)",
    ],
    "Lahore::Bahria Town Lahore": [
      "Sector A",
      "Sector B",
      "Sector C",
      "Sector D",
      "Sector E",
      "Sector F",
      "Janiper Block",
      "Jasmine Block",
      "Tulip Block",
      "Tauheed Block",
      "Tipu Sultan Block",
      "Iqbal Block",
      "Usman Block",
      "Umar Block",
      "Ali Block",
      "Nargis Block",
      "Chambelli Block",
      "Gulbahar Block",
      "Overseas Block",
      "Safari Villas",
      "Bahria Orchard",
      "Bahria Education & Medical City",
    ],
    "Lahore::Gulberg": [
      "Block A (Gulberg I)",
      "Block B (Gulberg I)",
      "Block C (Gulberg I)",
      "Block D (Gulberg I)",
      "Block E (Gulberg I)",
      "Gulberg II",
      "Gulberg III",
      "Gulberg IV (Garden Town)",
      "Hussain Chowk",
      "Liberty Market",
      "Main Boulevard Gulberg",
      "MM Alam Road",
    ],
    "Lahore::Model Town": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
      "Block H",
      "Block J",
      "Block K",
      "Block L",
      "Block M",
      "Block N",
      "Block P",
      "Block Q",
      "Block R",
      "Model Town Extension",
      "Model Town Link Road",
    ],
    "Lahore::Johar Town": [
      "Block A",
      "Block A-1",
      "Block A-2",
      "Block A-3",
      "Block B",
      "Block B-1",
      "Block B-2",
      "Block B-3",
      "Block C",
      "Block C-1",
      "Block C-2",
      "Block D",
      "Block D-1",
      "Block D-2",
      "Block E",
      "Block E-1",
      "Block E-2",
      "Block F",
      "Block F-1",
      "Block F-2",
      "Block G",
      "Block G-1",
      "Block G-2",
      "Block G-3",
      "Block H",
      "Block H-1",
      "Block H-2",
      "Block H-3",
      "Block J",
      "Block J-1",
      "Block J-2",
      "Block J-3",
      "Block K",
      "Block L",
      "Block M",
      "Block N",
      "Block P",
      "Block R",
      "Fazaia Housing Scheme",
    ],
    "Lahore::Wapda Town": [
      "Phase 1 - Block A",
      "Phase 1 - Block B",
      "Phase 1 - Block C",
      "Phase 1 - Block D",
      "Phase 1 - Block E",
      "Phase 1 - Block F",
      "Phase 1 - Block G",
      "Phase 1 - Block H",
      "Phase 1 - Block J",
      "Phase 1 - Block K",
      "Phase 2 - Block L",
      "Phase 2 - Block M",
      "Phase 2 - Block N",
      "Phase 2 - Block P",
      "Phase 2 - Block Q",
      "Phase 2 - Block R",
    ],
    "Lahore::Garden Town": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
    ],
    "Lahore::Township": [
      "Sector A-1",
      "Sector A-2",
      "Sector B-1",
      "Sector B-2",
      "Sector C-1",
      "Sector C-2",
      "Sector D-1",
      "Sector D-2",
    ],
    "Lahore::Cantt": [
      "Cantt Main",
      "Sarwar Road",
      "Mall Road Cantt",
      "Saddar Cantt",
      "Askari 9",
      "Askari 10",
      "Askari 11",
    ],
    "Lahore::Iqbal Town": [
      "Karim Block",
      "Nizam Block",
      "Hunza Block",
      "Ravi Block",
      "Mehran Block",
      "Neelam Block",
      "Kamran Block",
      "Khyber Block",
      "Rachna Block",
      "Satluj Block",
      "Chenab Block",
      "Jhelum Block",
      "Indus Block",
      "Kabir Town",
    ],
    "Lahore::Faisal Town": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
    ],
    "Lahore::EME Society": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
    ],
    "Lahore::Valencia Town": [
      "Block A",
      "Block A-1",
      "Block B",
      "Block B-1",
      "Block C",
      "Block C-1",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
      "Block H",
      "Block J",
    ],
    "Lahore::PCSIR Housing Scheme": [
      "Phase 1",
      "Phase 2",
    ],
    "Lahore::Punjab Cooperative Housing Society (PCHS)": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
    ],
    "Lahore::Cavalry Ground": [
      "Cavalry Ground Extension",
      "Main Cavalry Ground",
    ],
    "Lahore::Sui Gas Society": [
      "Phase 1",
      "Phase 2",
    ],
    "Lahore::Lake City": [
      "Sector M-1",
      "Sector M-2",
      "Sector M-2A",
      "Sector M-3",
      "Sector M-3 Extension",
      "Sector M-5",
      "Sector M-7",
      "Sector M-8",
      "Raiwind Road",
    ],
    "Lahore::State Life Housing Society": [
      "Phase 1",
      "Phase 2",
      "Phase 3",
    ],
    "Lahore::PGEHS (Punjab Govt Employees Housing Scheme)": [
      "Phase 1",
      "Phase 2",
      "Phase 3",
    ],
    "Lahore::LDA Avenue": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
      "Block H",
      "Block J",
      "Block K",
    ],
    "Lahore::Jubilee Town": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
    ],
    "Lahore::Sabzazar": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
      "Block H",
      "Block J",
      "Block K",
      "Block L",
      "Block M",
      "Block N",
      "Block P",
    ],
    "Lahore::Shahdara": [
      "Shahdara Main",
      "Shahdara Town",
    ],
    "Lahore::Shadman": [
      "Shadman 1",
      "Shadman 2",
    ],
    "Karachi::DHA": [
      "Phase 1",
      "Phase 2",
      "Phase 2 Extension",
      "Phase 3",
      "Phase 4",
      "Phase 5",
      "Phase 6",
      "Phase 7",
      "Phase 7 Extension",
      "Phase 8",
      "Phase 8 Extension",
      "Phase 9 (Creek Vista)",
    ],
    "Karachi::Clifton": [
      "Block 1",
      "Block 2",
      "Block 3",
      "Block 4",
      "Block 5",
      "Block 6",
      "Block 7",
      "Block 8",
      "Block 9",
      "Kehkashan",
      "Zamzama",
      "Sea View",
      "Delhi Colony",
      "Punjab Colony",
      "Shah Rasool Colony",
    ],
    "Karachi::PECHS": [
      "Block 1",
      "Block 2",
      "Block 3",
      "Block 4",
      "Block 5",
      "Block 6",
      "Block 7",
      "Khalid Bin Walid Road",
      "Tariq Road",
    ],
    "Karachi::Gulshan-e-Iqbal": [
      "Shanti Nagar",
      "Block 1",
      "Block 2",
      "Block 3",
      "Block 4",
      "Block 4-A",
      "Block 5",
      "Block 6",
      "Block 7",
      "Block 8",
      "Block 9",
      "Block 10",
      "Block 10-A",
      "Block 11",
      "Block 12",
      "Block 13",
      "Block 13-A",
      "Block 13-B",
      "Block 13-C",
      "Block 13-D",
      "Block 14",
      "Block 15",
      "Block 16",
      "Block 17",
      "Block 18",
      "Block 19",
      "Adamjee Nagar",
      "Civic Center",
      "Dhoraji",
      "University Road",
    ],
    "Karachi::Gulistan-e-Jauhar": [
      "Block 1",
      "Block 2",
      "Block 3",
      "Block 3-A",
      "Block 4",
      "Block 5",
      "Block 6",
      "Block 7",
      "Block 8",
      "Block 9",
      "Block 10",
      "Block 11",
      "Block 12",
      "Block 13",
      "Block 14",
      "Block 15",
      "Block 16",
      "Block 17",
      "Block 18",
      "Block 19",
      "Block 20",
    ],
    "Karachi::North Karachi": [
      "Sector 2",
      "Sector 3",
      "Sector 4",
      "Sector 5-A/1",
      "Sector 5-A/2",
      "Sector 5-A/3",
      "Sector 5-A/4",
      "Sector 5-B/1",
      "Sector 5-B/2",
      "Sector 5-B/3",
      "Sector 5-B/4",
      "Sector 5-C/1",
      "Sector 5-C/2",
      "Sector 5-C/3",
      "Sector 5-C/4",
      "Sector 5-I",
      "Sector 5-J",
      "Sector 5-K",
      "Sector 5-L",
      "Sector 5-M",
      "Sector 6",
      "Sector 7-D/1",
      "Sector 7-D/2",
      "Sector 7-D/3",
      "Sector 7-D/4",
      "Sector 8",
      "Sector 9",
      "Sector 10",
      "Sector 11-A",
      "Sector 11-B",
      "Sector 11-C/1",
      "Sector 11-C/2",
      "Sector 11-C/3",
      "Sector 11-E",
      "Sector 11-H",
      "Sector 11-I",
      "Sector 11-K",
      "Sector 11-L",
      "Sector 12-A",
      "Sector 12-C",
    ],
    "Karachi::North Nazimabad": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
      "Block H",
      "Block I",
      "Block J",
      "Block K",
      "Block L",
      "Block M",
      "Block N",
      "Block O",
      "Block P",
      "Block Q",
      "Block R",
      "Block S",
      "Block T",
      "Block W",
    ],
    "Karachi::Nazimabad": [
      "Block 1",
      "Block 2",
      "Block 3",
      "Block 4",
      "Block 5",
    ],
    "Karachi::Federal B. Area": [
      "Gulshan-e-Shamim",
      "Block 1 (Sharifabad)",
      "Block 2 (Sharifabad)",
      "Block 3 (Hussainabad)",
      "Block 4 (Tayyababad)",
      "Block 5 (Tayyababad)",
      "Block 6 (Tayyababad)",
      "Block 7 (Azizabad)",
      "Block 8 (Azizabad)",
      "Block 9",
      "Block 10 (Dastagir)",
      "Block 11",
      "Block 12",
      "Block 13",
      "Block 14 (Naseerabad)",
      "Block 15 (Naseerabad)",
      "Block 16 (Water Pump)",
      "Block 17 (Samanabad)",
      "Block 18 (Samanabad)",
      "Block 19 (Al-Noor Society)",
      "Block 20 (Ancholi)",
      "Block 21 (Industrial Area)",
      "Block 22 (Industrial Area)",
      "B Area",
      "B1 Area",
      "Azizabad",
    ],
    "Karachi::Liaquatabad": [
      "Block 1",
      "Block 2",
      "Block 3",
      "Block 4",
      "Block 5",
      "Block 6",
      "Block 7",
      "Block 8",
      "Block 9",
      "Block 10",
    ],
    "Karachi::Korangi": [
      "Darussalam Society",
      "Sector 31-B",
      "Sector 31-D",
      "Sector 32-B",
      "Sector 33-A",
      "Sector 33-B",
      "Sector 33-C",
      "Sector 33-D",
      "Sector 33-E",
      "Sector 33-F",
      "Sector 41-B",
      "Korangi Industrial Area",
      "Nasir Colony",
      "Zaman Town",
      "Zia Colony",
      "Mehran Town",
      "PAF Base Korangi Creek",
      "Abdullah Shah Noorani Pahari Colony",
    ],
    "Karachi::Landhi": [
      "36-B",
      "Awami Colony",
      "Labour Colony",
      "Landhi Industrial Area",
      "Bagh-e-Korangi",
      "Bakhtawar Goth",
      "Bhutto Nagar",
      "Future Colony",
      "Gulshan-e-Rafi",
      "Ilyas Goth",
      "Muslimabad Colony",
      "Muzaffarabad Colony",
      "Punjab Town",
      "Qasim Town",
      "Sadat Colony",
      "Shah Khalid Colony",
      "Sharafi Goth",
      "Zamanabad",
      "Barmi Colony",
      "Alflah Housing Society",
    ],
    "Karachi::Malir": [
      "Malir Town",
      "Malir Cantt",
      "Malir City",
      "Malir Halt",
      "Malir Extension",
      "Model Colony",
    ],
    "Karachi::Shah Faisal Colony": [
      "Shah Faisal Colony 1",
      "Shah Faisal Colony 2",
      "Shah Faisal Colony 3",
      "Shah Faisal Colony 4",
      "Shah Faisal Colony 5",
      "Aswan Town",
      "Gulshan-e-Asghar",
      "Green Town",
      "Shamsi Society",
      "Muslimabad Malir City",
    ],
    "Karachi::Bahria Town Karachi": [
      "Precinct 1",
      "Precinct 2",
      "Precinct 3",
      "Precinct 4",
      "Precinct 5",
      "Precinct 6",
      "Precinct 7",
      "Precinct 8",
      "Precinct 9",
      "Precinct 10",
      "Precinct 11",
      "Precinct 12",
      "Precinct 13",
      "Precinct 14",
      "Precinct 15",
      "Precinct 16",
      "Precinct 17",
      "Precinct 18",
      "Precinct 19",
      "Precinct 20",
      "Precinct 21",
      "Precinct 22",
      "Precinct 23",
      "Precinct 24",
      "Precinct 25",
      "Precinct 26",
      "Precinct 27",
      "Precinct 28",
      "Precinct 29",
      "Precinct 30",
      "Precinct 31",
      "Precinct 32",
      "Precinct 33",
    ],
    "Karachi::Askari": [
      "Askari 1",
      "Askari 2",
      "Askari 3",
      "Askari 4",
      "Askari 5",
    ],
    "Karachi::Buffer Zone": [
      "Sector 15-A/1",
      "Sector 15-A/2",
      "Sector 15-A/3",
      "Sector 15-A/4",
      "Sector 15-A/5",
      "Sector 15-B",
      "Sector 16-A",
      "Sector 16-B",
    ],
    "Karachi::Gulshan-e-Hadeed": [
      "Phase 1",
      "Phase 2",
      "Phase 3",
      "Steel Town",
      "Shah Latif Town",
      "Data Nagar",
      "Gulshan-e-Mauzzam",
      "Gulshan-e-Rehman",
      "Mehran Road",
    ],
    "Karachi::Garden": [
      "Garden East",
      "Garden West",
      "Soldier Bazaar",
    ],
    "Karachi::Orangi Town": [
      "Data Nagar",
      "Sector 14-A",
      "Sector 14-C",
      "Banaras Town",
      "Bangla Bazaar",
      "Bilal Colony",
      "Katti Pahari",
      "Moria Goth",
      "Orangi",
    ],
    "Karachi::Saddar": [
      "Saddar",
      "Kharadar",
      "Mithadar",
      "Jodia Bazar",
      "Bombay Bazar",
      "Lee Market",
      "Bohri Bazaar",
      "Ranchore Line",
      "Nanakwara",
      "Nishtar Road",
      "Pan Mandi",
      "Kagzi Bazar",
      "Kakri Ground",
      "Aram Bagh",
      "Napier Quarter",
      "Civil Line",
      "I.I. Chundrigar Road",
    ],
    "Karachi::KAECHS": [
      "Block 1",
      "Block 2",
      "Block 3",
      "Block 4",
    ],
    "Karachi::Gulshan-e-Maymar": [
      "Sector W",
      "Sector X",
      "Sector Y",
      "Sector Z",
    ],
    "Karachi::Scheme 33": [
      "Memon Nagar",
      "Sector 14-A",
      "Sector 15-A",
      "Sector 17-A",
      "Sector 20-A",
      "Sector 21-A",
      "Sector 22-A",
      "Sector 23-A",
      "Sector 24-A",
      "Sector 25-A",
      "Sector 34-A",
    ],
    "Karachi::New Karachi": [
      "Sector 1",
      "Sector 2",
      "Sector 3",
      "Sector 4",
      "Sector 5",
    ],
    "Karachi::Defence View": [
      "Phase 1",
      "Phase 2",
    ],
    "Karachi::Gulzar-e-Hijri": [
      "Scheme 33 Extension",
      "Main Area",
    ],
    "Karachi::Surjani Town": [
      "Sector 1",
      "Sector 2",
      "Sector 3",
      "Sector 4",
      "Sector 5",
      "Sector 6",
      "Sector 7",
      "Sector 8",
    ],
    "Karachi::Naya Nazimabad": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block M",
    ],
    "Islamabad::Sector E-7": [
      "E-7/1",
      "E-7/2",
      "E-7/3",
      "E-7/4",
    ],
    "Islamabad::Sector E-8": [
      "E-8/1",
      "E-8/2",
      "E-8/3",
      "E-8/4",
    ],
    "Islamabad::Sector E-9": [
      "E-9/1",
      "E-9/2",
      "E-9/3",
      "E-9/4",
    ],
    "Islamabad::Sector E-10": [
      "E-10/1",
      "E-10/2",
      "E-10/3",
      "E-10/4",
    ],
    "Islamabad::Sector E-11": [
      "E-11/1",
      "E-11/2",
      "E-11/3",
      "E-11/4",
    ],
    "Islamabad::Sector E-12": [
      "E-12/1",
      "E-12/2",
      "E-12/3",
      "E-12/4",
    ],
    "Islamabad::Sector E-16": [
      "E-16/1",
      "E-16/2",
      "E-16/3",
      "E-16/4",
    ],
    "Islamabad::Sector E-17": [
      "E-17/1",
      "E-17/2",
      "E-17/3",
      "E-17/4",
    ],
    "Islamabad::Sector F-5": [
      "F-5/1",
      "F-5/2",
      "F-5/3",
      "F-5/4",
    ],
    "Islamabad::Sector F-6": [
      "F-6/1",
      "F-6/2",
      "F-6/3",
      "F-6/4",
      "F-6 Markaz (Super Market)",
    ],
    "Islamabad::Sector F-7": [
      "F-7/1",
      "F-7/2",
      "F-7/3",
      "F-7/4",
      "F-7 Markaz (Jinnah Super)",
    ],
    "Islamabad::Sector F-8": [
      "F-8/1",
      "F-8/2",
      "F-8/3",
      "F-8/4",
      "F-8 Markaz",
    ],
    "Islamabad::Sector F-9 (Fatima Jinnah Park)": [
      "F-9/1",
      "F-9/2",
      "F-9/3",
      "F-9/4",
      "F-9 Park",
    ],
    "Islamabad::Sector F-10": [
      "F-10/1",
      "F-10/2",
      "F-10/3",
      "F-10/4",
      "F-10 Markaz",
    ],
    "Islamabad::Sector F-11": [
      "F-11/1",
      "F-11/2",
      "F-11/3",
      "F-11/4",
      "F-11 Markaz",
    ],
    "Islamabad::Sector F-17": [
      "F-17/1",
      "F-17/2",
      "F-17/3",
      "F-17/4",
    ],
    "Islamabad::Sector G-5": [
      "G-5/1",
      "G-5/2",
      "G-5/3",
      "G-5/4",
    ],
    "Islamabad::Sector G-6": [
      "G-6/1",
      "G-6/2",
      "G-6/3",
      "G-6/4",
      "G-6 Markaz (Melody Market)",
    ],
    "Islamabad::Sector G-7": [
      "G-7/1",
      "G-7/2",
      "G-7/3",
      "G-7/4",
    ],
    "Islamabad::Sector G-8": [
      "G-8/1",
      "G-8/2",
      "G-8/3",
      "G-8/4",
      "G-8 Markaz",
    ],
    "Islamabad::Sector G-9": [
      "G-9/1",
      "G-9/2",
      "G-9/3",
      "G-9/4",
      "G-9 Markaz (Karachi Company)",
    ],
    "Islamabad::Sector G-10": [
      "G-10/1",
      "G-10/2",
      "G-10/3",
      "G-10/4",
      "G-10 Markaz",
    ],
    "Islamabad::Sector G-11": [
      "G-11/1",
      "G-11/2",
      "G-11/3",
      "G-11/4",
      "G-11 Markaz",
    ],
    "Islamabad::Sector G-12": [
      "G-12/1",
      "G-12/2",
      "G-12/3",
      "G-12/4",
    ],
    "Islamabad::Sector G-13": [
      "G-13/1",
      "G-13/2",
      "G-13/3",
      "G-13/4",
    ],
    "Islamabad::Sector G-14": [
      "G-14/1",
      "G-14/2",
      "G-14/3",
      "G-14/4",
    ],
    "Islamabad::Sector G-15": [
      "G-15/1",
      "G-15/2",
      "G-15/3",
      "G-15/4",
    ],
    "Islamabad::Sector G-16": [
      "G-16/1",
      "G-16/2",
      "G-16/3",
      "G-16/4",
    ],
    "Islamabad::Sector H-8": [
      "H-8/1",
      "H-8/2",
      "H-8/3",
      "H-8/4",
    ],
    "Islamabad::Sector H-9": [
      "H-9/1",
      "H-9/2",
      "H-9/3",
      "H-9/4",
    ],
    "Islamabad::Sector H-10": [
      "H-10/1",
      "H-10/2",
      "H-10/3",
      "H-10/4",
    ],
    "Islamabad::Sector H-11": [
      "H-11/1",
      "H-11/2",
      "H-11/3",
      "H-11/4",
    ],
    "Islamabad::Sector H-12": [
      "H-12/1",
      "H-12/2",
      "H-12/3",
      "H-12/4",
    ],
    "Islamabad::Sector H-13": [
      "H-13/1",
      "H-13/2",
      "H-13/3",
      "H-13/4",
    ],
    "Islamabad::Sector I-8": [
      "I-8/1",
      "I-8/2",
      "I-8/3",
      "I-8/4",
      "I-8 Markaz",
    ],
    "Islamabad::Sector I-9": [
      "I-9/1",
      "I-9/2",
      "I-9/3",
      "I-9/4",
      "I-9 Industrial Area",
    ],
    "Islamabad::Sector I-10": [
      "I-10/1",
      "I-10/2",
      "I-10/3",
      "I-10/4",
      "I-10 Markaz",
    ],
    "Islamabad::Sector I-11": [
      "I-11/1",
      "I-11/2",
      "I-11/3",
      "I-11/4",
    ],
    "Islamabad::Sector I-12": [
      "I-12/1",
      "I-12/2",
      "I-12/3",
      "I-12/4",
    ],
    "Islamabad::Sector I-14": [
      "I-14/1",
      "I-14/2",
      "I-14/3",
      "I-14/4",
    ],
    "Islamabad::Sector I-15": [
      "I-15/1",
      "I-15/2",
      "I-15/3",
      "I-15/4",
    ],
    "Islamabad::Sector I-16": [
      "I-16/1",
      "I-16/2",
      "I-16/3",
      "I-16/4",
    ],
    "Islamabad::Blue Area": [
      "Jinnah Avenue",
      "Blue Area Commercial",
    ],
    "Islamabad::Sector D-12": [
      "D-12/1",
      "D-12/2",
      "D-12/3",
      "D-12/4",
    ],
    "Islamabad::Sector D-17": [
      "D-17/1",
      "D-17/2",
    ],
    "Islamabad::Sector C-14": [
      "C-14/1",
      "C-14/2",
      "C-14/3",
      "C-14/4",
    ],
    "Islamabad::Sector C-15": [
      "C-15/1",
      "C-15/2",
      "C-15/3",
      "C-15/4",
    ],
    "Islamabad::Sector B-17": [
      "Block A",
      "Block B",
      "Block C",
      "Block C-1",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
    ],
    "Islamabad::DHA Islamabad": [
      "Phase 1",
      "Phase 2",
      "Phase 2 Extension",
      "Phase 3",
      "Phase 4",
      "Phase 5",
      "DHA Valley",
    ],
    "Islamabad::Bahria Town Islamabad": [
      "Phase 1",
      "Phase 2",
      "Phase 3",
      "Phase 4",
      "Phase 5",
      "Phase 6",
      "Phase 7",
      "Phase 8",
      "Bahria Enclave - Sector A",
      "Bahria Enclave - Sector B",
      "Bahria Enclave - Sector C",
      "Bahria Enclave - Sector D",
      "Bahria Enclave - Sector E",
      "Bahria Enclave - Sector F",
      "Bahria Enclave - Sector G",
      "Bahria Enclave - Sector H",
      "Bahria Enclave - Sector I",
      "Bahria Enclave - Sector N",
      "Civic Center",
      "Safari Valley",
      "Safari Villas",
      "Bahria Spring",
      "Bahria Garden City",
    ],
    "Islamabad::PWD Housing Scheme": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
    ],
    "Islamabad::Pakistan Town": [
      "Phase 1",
      "Phase 2",
    ],
    "Islamabad::CBR Town": [
      "Phase 1",
      "Phase 2",
    ],
    "Islamabad::Gulberg Greens": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
    ],
    "Islamabad::Gulberg Residencia": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
      "Block H",
      "Block I",
    ],
    "Islamabad::Top City": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
    ],
    "Islamabad::Capital Smart City": [
      "Executive Block",
      "Overseas Block",
      "General Block",
      "Harmony Park",
      "Overseas East",
    ],
    "Rawalpindi::Satellite Town": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
    ],
    "Rawalpindi::Bahria Town Phase 8": [
      "Umer Block",
      "Ali Block",
      "Abu Baker Block",
      "Usman Block",
      "Rafi Block",
      "Khalid Block",
      "Awami Villas",
      "Lake View",
      "Safari Home",
      "Overseas Enclave",
    ],
    "Rawalpindi::Chaklala Scheme 3": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
    ],
    "Rawalpindi::Askari": [
      "Askari 1",
      "Askari 2",
      "Askari 3",
      "Askari 5",
      "Askari 11",
      "Askari 14",
    ],
    "Rawalpindi::Westridge": [
      "Block 1",
      "Block 2",
      "Block 3",
    ],
    "Rawalpindi::Adiala Road": [
      "Gulraiz Housing Society Phase 1",
      "Gulraiz Housing Society Phase 2",
      "Gulraiz Housing Society Phase 3",
      "Gulraiz Housing Society Phase 4",
      "Gulraiz Housing Society Phase 5",
      "Media Town",
      "Airport Housing Society",
    ],
    "Rawalpindi::Saddar": [
      "Saddar Main",
      "Committee Chowk",
      "Bank Road",
      "Murree Road",
      "Haider Road",
    ],
    "Rawalpindi::Rawalpindi Cantt": [
      "Mall Road",
      "The Mall",
      "Cantt Bazaar",
      "Chaklala Cantt",
    ],
    "Faisalabad::Peoples Colony": [
      "No. 1",
      "No. 2",
    ],
    "Faisalabad::Madina Town": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
    ],
    "Faisalabad::Gulberg": [
      "Block A",
      "Block B",
      "Block C",
    ],
    "Faisalabad::Samanabad": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
    ],
    "Faisalabad::Ghulam Muhammad Abad": [
      "Phase 1",
      "Phase 2",
    ],
    "Faisalabad::Batala Colony": [
      "Old Batala Colony",
      "New Batala Colony",
    ],
    "Faisalabad::Jinnah Colony": [
      "Block A",
      "Block B",
      "Block C",
    ],
    "Faisalabad::Eden Valley": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
    ],
    "Faisalabad::Citi Housing": [
      "Phase 1",
      "Phase 2",
      "Phase 3",
    ],
    "Faisalabad::Wapda City": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
    ],
    "Peshawar::Hayatabad": [
      "Phase 1 - Sector E-1",
      "Phase 1 - Sector E-2",
      "Phase 1 - Sector E-3",
      "Phase 1 - Sector E-4",
      "Phase 1 - Sector E-5",
      "Phase 2 - Sector E-6",
      "Phase 2 - Sector E-7",
      "Phase 2 - Sector E-8",
      "Phase 3 - Sector E-9",
      "Phase 3 - Sector E-10",
      "Phase 4 - Sector D-1",
      "Phase 4 - Sector D-2",
      "Phase 4 - Sector D-3",
      "Phase 5 - Sector D-4",
      "Phase 5 - Sector D-5",
      "Phase 6 - Sector F-1",
      "Phase 6 - Sector F-2",
      "Phase 6 - Sector F-3",
      "Phase 6 - Sector F-5",
      "Phase 6 - Sector F-6",
      "Phase 6 - Sector F-7",
      "Phase 6 - Sector F-8",
      "Phase 7 - Sector F-9",
      "Phase 7 - Sector F-10",
    ],
    "Peshawar::University Town": [
      "Main University Town",
      "Abdara Road",
      "Arbab Road",
      "University Road",
    ],
    "Peshawar::Peshawar Cantt": [
      "Cantt Main",
      "Saddar",
      "Mall Road",
    ],
    "Peshawar::DHA Peshawar": [
      "Sector A",
      "Sector B",
      "Sector C",
      "Sector D",
      "Sector E",
      "Sector F",
      "Sector G",
    ],
    "Peshawar::Regi Model Town": [
      "Zone 1",
      "Zone 2",
      "Zone 3",
      "Zone 4",
      "Zone 5",
    ],
    "Peshawar::Warsak Road": [
      "Board Bazaar",
      "Danish Abad",
      "Gulbahar",
      "Shahi Bagh",
    ],
    "Quetta::Satellite Town": [
      "Block 1",
      "Block 2",
      "Block 3",
      "Block 4",
    ],
    "Quetta::Cantonment": [
      "Cantt Main",
      "Jinnah Road",
      "Staff College Road",
    ],
    "Quetta::Samungli": [
      "Samungli Road",
      "Airport Road",
      "PAF Base",
    ],
    "Multan::DHA Multan": [
      "Sector A",
      "Sector B",
      "Sector C",
      "Sector D",
      "Sector E",
      "Sector F",
      "Sector G",
      "Sector H",
      "Sector I",
      "Sector J",
      "Sector K",
      "Sector L",
      "Sector M",
      "Sector N",
      "Sector P",
      "Sector Q",
      "Sector R",
      "Sector S",
      "Sector T",
      "Sector U",
      "Sector V",
      "Villas Sector",
    ],
    "Multan::Bosan Road": [
      "Block A",
      "Block B",
      "Block C",
    ],
    "Multan::Shah Rukn-e-Alam Colony": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
      "Extension",
    ],
    "Multan::Gulgasht Colony": [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
    ],
    "Multan::Wapda Town": [
      "Phase 1",
      "Phase 2",
    ],
    "Multan::Officers Colony": [
      "Block A",
      "Block B",
      "Block C",
    ],
    "Multan::Model Town": [
      "Block A",
      "Block B",
      "Block C",
    ],
    "Multan::Citi Housing Multan": [
      "Phase 1",
      "Phase 2",
    ],
    "Hyderabad::Latifabad": [
      "Unit 1",
      "Unit 2",
      "Unit 3",
      "Unit 4",
      "Unit 5",
      "Unit 6",
      "Unit 7",
      "Unit 8",
      "Unit 9",
      "Unit 10",
      "Unit 11",
      "Unit 12",
    ],
    "Hyderabad::Qasimabad": [
      "Phase 1",
      "Phase 2",
      "Revenue Housing Society",
      "Naseem Nagar",
      "Alamdar Chowk",
    ],
    "Hyderabad::Cantonment": [
      "Cantt Main",
      "Saddar",
      "Thandi Sarak",
    ],
    "Hyderabad::Gulshan-e-Shahbaz": [
      "Phase 1",
      "Phase 2",
    ],
  },
};
